version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./infra/docker/web/default-dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    container_name: laravel_web

  app:
    build:
      context: .
      dockerfile: ./infra/docker/app/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    container_name: laravel_app
